{% set name = "atap_widgets" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atap_widgets-{{ version }}.tar.gz
  sha256: 0a280b51934128eb281bd394874e04ace39d077af4b0a50043e02f7a62839ab5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python >=3.6,<3.11
  run:
    - python

test:
  imports:
    - atap_widgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Australian-Text-Analytics-Platform/atap_widgets
  summary: Interactive widgets used by the Australian Text Analytics Platform
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marius-mather
