{% set name = "atap_widgets" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/atap_widgets-{{ version }}.tar.gz
  sha256: 0a280b51934128eb281bd394874e04ace39d077af4b0a50043e02f7a62839ab5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<3.12
    - bokeh >=2.0,<3.0
    - ipywidgets >=8.0,<9.0
    - pandas >=1.3,<2.0
    - spacy >=3.0,<4.0
    - textacy
    - xlsxwriter >=3,<4

test:
  imports:
    - atap_widgets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Australian-Text-Analytics-Platform/atap_widgets
  summary: Interactive widgets used by the Australian Text Analytics Platform
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marius-mather
