{% set name = "atap_widgets" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atap_widgets-{{ version }}.tar.gz
  sha256: b82a072c5aed1d686278efb83d1b5cf58cb2a1fc4ce10a3bb438457386ab6eb9
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<3.11
  run:
    - bokeh >=2.4,<3.0
    - ipywidgets >=7.6,<8.0
    - pandas >=1.3,<2.0
    - python >=3.6,<3.11
    - spacy >=3.1,<4.0
    - textacy
    - xlsxwriter >=3.0.2,<4.0.0

test:
  imports:
    - atap_widgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Australian-Text-Analytics-Platform/atap_widgets
  summary: Interactive widgets used by the Australian Text Analytics Platform
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marius-mather
